language: php

php:
  - 5.5
  - 5.4
  - 5.3

services:
  - mysql

before_script:
  - cp app/config/parameters.dist.yml app/config/parameters.yml
  - mysql -e 'create database testdb;'
  - php composer.phar install

script: bin/phpunit -c app/

notifications:
  email:
    recipients:
      - michael@phpbb.com
    on_success: always
    on_failure: always

branches:
  only:
    master
