language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - sh -c pyrus install --force phpunit/DbUnit
  - phpenv rehash
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php composer.phar install

script: bin/phpunit -c app/

notifications:
  email:
    recipients:
      - michael@phpbb.com
    on_success: always
    on_failure: always

branches:
  only:
    master
