parameters:
#    php_bb_status_site.example.class: phpBB\StatusSiteBundle\Example

services:
#    php_bb_status_site.example:
#        class: %php_bb_status_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
